### PR TITLE
chore(RHIF-169): hide system update method filter untill API is ready

### PR DESCRIPTION
**Pull request by mkholjuraev**
Hides the System update method filter with a feature flag.

1. Run the PR locally on the stage environment.
2. Go to https://insights-stage.unleash.devshift.net/projects/default/features/hbi.ui.system-update-method.
3. Set the flag to true in default and then observe that the filter is shown.
4. Set the flag to false in default and then observe that the filter is hidden.

### CODE REVIEW

**Comment by computercamplove** [comment]
@mkholjuraev do we need to create this feature on prod https://insights.unleash.devshift.net/ to hide it there?

**Comment by mkholjuraev** [comment]
@computercamplove yup, I am creating one in prod.

**Review by adonispuente — APPROVED** [review]
PR works as intended, LGTM!

**Pull request merged**
