### PR TITLE
feat(ESSNTL-4365): Enable actions in the groups table

### PR DESCRIPTION
**Pull request by gkarat**
Implements https://issues.redhat.com/browse/ESSNTL-4365.

- Connects modals to the appropriate action buttons in the groups table.
- Improves the delete group modal so that it can accept more group IDs and perform the deletion request with multiple IDs.

## How to test:

1.  Run `npm run mock-server` and `npm run start:mock:beta` in separate terminals.
2. Navigate to https://stage.foo.redhat.com:1337/beta/insights/inventory/groups.
3. Use toolbar or per-row actions kebab to use the features on selected groups.
4. Check the right network requests are made after performing any action. (visually there can be some bugs due to the mocked crazy API).
5. Check the components tests pass.

## Screenshots

image

image

image

### CODE REVIEW

**Comment by gkarat** [comment]
Putting to draft state, gonna add one more commit to enable multiple groups deletion...

**Review by Fewwy — APPROVED** [review]
Tested it locally. LGTM

**Pull request merged**
