### PR TITLE
feat(ESSNTL-4935): Should disable actions at /groups

### PR DESCRIPTION
**Pull request by gkarat**
Implements https://issues.redhat.com/browse/ESSNTL-4935.

The /groups view must disable actions if users don't have `inventory:groups:write` permission.

image

### CODE REVIEW

**Comment by gkarat** [comment]
Putting to draft: there came some new UX requirements

**Comment by gkarat** [comment]
Now ready for review :)

**Review by Fewwy — APPROVED** [review]

**Pull request merged**
