### PR TITLE
test(RHINENG-8182): Update cypress tests after PF5 upgrade

### PR DESCRIPTION
**Pull request by gkarat**
Fixes https://issues.redhat.com/browse/RHINENG-8182.

Follows up on: https://github.com/RedHatInsights/insights-inventory-frontend/pull/2141
Blocked by https://github.com/RedHatInsights/frontend-components/pull/1968

This enables back the cypress test in Travis CI and makes them pass by updating selectors after PF5 migration.

### CODE REVIEW

**Comment by gkarat** [comment]
@computercamplove, by any chance, is there something in e2e tests that caused by this PR?

**Review by mkholjuraev — APPROVED** [review]
@gkarat thank you, I could not spot anything to suggest. All looks great!

**Pull request merged**
