### PR TITLE
RHINENG-7656 fixed ros tab missing in inventory details page

### PR DESCRIPTION
**Pull request by PreetiW**
RHINENG-7656 fixed ros tab missing in inventory details page

Jira: https://issues.redhat.com/browse/RHINENG-7656

### CODE REVIEW

**Comment by PreetiW** [comment]
@RedHatInsights/team-interact can someone check and tell me why the job is failing? I don't have enough permissions to check the logs.

**Comment by leSamo** [comment]
@PreetiW the commit title linter is failing:
> ⧗   input: RHINENG-7656 fixed ros tab missing in inventory details page
> ✖   subject may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]

The commit title should be in this format:
`fix(<Jira ticket>): <description>`

**Review by mkholjuraev — APPROVED** [review]
LGTM codewise!

**Comment by PreetiW** [comment]
Thank you for the reviewing and approving the PR @mkholjuraev 🙌🏻  I have rebased the PR. Can you or someone please merge the PR as I don't have right to do the same!

**Pull request merged**
