### PR TITLE
fix(RHIF-72): Fix InventoryTable font size and actions button padding

### PR DESCRIPTION
**Pull request by gkarat**
Fixes https://issues.redhat.com/browse/RHIF-72.

- Changes the InventoryTable rows text to have font size 14 px.
- Fixes the actions (kebab) button styling so that it is equally distanced from both sides.

Before

Screenshot 2023-11-03 at 17 47 54

After

Screenshot 2023-11-03 at 17 45 56

### CODE REVIEW

**Review by AsToNlele — CHANGES_REQUESTED** [review]
Thank you for the fix @gkarat! :smile:  The font size is finally consistent between the apps

Just a small nitpick, I believe the kebab on the right side should have 24px padding from the right side, not 16px. Feel free to correct me

**Comment by gkarat** [comment]
You are right, the spacing for the default variant table is 24 px: https://v4-archive.patternfly.org/v4/components/table/design-guidelines#default-spacing. Will fix it now

**Comment by gkarat** [comment]
@AsToNlele, it's fixed now

**Review by AsToNlele — APPROVED** [review]
Perfect, thank you @gkarat! :smile:

**Pull request merged**
