### PR TITLE
chore(deps): Bump @redhat-cloud-services & @patternfly packages

### PR DESCRIPTION
**Pull request by bastilian**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
Ah it actually requires a tsconfig to exist, welp. Expect a hotfix soon.

**Comment by bastilian** [comment]
Thank you @Hyperkid123!

**Comment by Hyperkid123** [comment]
@bastilian this should fix it: https://github.com/RedHatInsights/frontend-components/pull/1643

**Review by gkarat — APPROVED** [review]
LGTM, run fine locally

**Pull request merged**
