### PR TITLE
Add delete operation to inventory table

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2019-06-26 14-43-16
Screenshot from 2019-06-26 14-44-01
Screenshot from 2019-06-26 14-44-12

### CODE REVIEW

**Comment by karelhala** [comment]
ping @bclarhk

**Comment by bclarhk** [comment]
Looks good! The toast messages need to be tweaked- my fault for not including them earlier.

Success message:
<system name> has been successfully removed.

Started:
Removal of <system name> started.

**Comment by karelhala** [comment]
@bclarhk thanks for the review! Changed the messages to
```
Delete operation initiated
Removal of ${displayName} started.
```
```
Delete operation finished
${displayName} has been successfully removed.
```

**Comment by karelhala** [comment]
Updated toast notification:
Screenshot from 2019-07-02 17-44-46

**Pull request merged**
