### PR TITLE
fix(ESSNTL-3730): Fix Add host to group API call

### PR DESCRIPTION
**Pull request by gkarat**
Fixes https://issues.redhat.com/browse/ESSNTL-3730.

This makes the "add host to group" modal pass correct host ID and thus send correct API request. Previously, the group's ID in the network request was always equal to `undefined`.

## How to test

1. Run `npm run start:proxy:beta`
2. Authenticate with `insights-qa`, navigate to https://stage.foo.redhat.com:1337/preview/insights/inventory.
3. Select any system and add it to a group.
4. After submit, in the network tab, make sure the POST /groups/... request contains correct ids of both group and added system.

### CODE REVIEW

**Review by Fewwy — APPROVED** [review]
LGTM

**Comment by mkholjuraev** [comment]
It seems only host_id is passed to API?

**Comment by gkarat** [comment]
@mkholjuraev, hm, what's the full URL of the request? the URL must contain both the group id and the host id. The format is `POST /v1/groups/%groupId/hosts/%hostId`. But it's strange we also send the request body... I will change it now so that we don't append any extra info...

**Comment by gkarat** [comment]
@mkholjuraev ,yeah, this looks as expected: URL contains both valid group and host IDs. the endpoint is not yet implemented, so the 405 code is also correct for now

**Pull request merged**
