### PR TITLE
fix(vulnerability): Fix padding issue in vuln sysdetails page

### PR DESCRIPTION
**Pull request by adonispuente**
Fixes the padding issue inside vulnerability sys details page:

To replicate the issue, just go to any sysdetails in vulnerability
before there is a massive gap inbetween the table and header: 
Screenshot 2024-08-07 at 2 59 41 PM

### CODE REVIEW

**Review by mkholjuraev — APPROVED** [review]
LGTM! @adonispuente  thank you for the quick fix. Let's discuss the real cause tomorrow

**Comment by adonispuente** [comment]
@computercamplove This ci test is failing with `18:36:45 ��� ERROR: tests hit errors or failed to collect for plugins: ['host_inventory_frontend']
`, Are you aware of anything on the QE side of this that could cause that?

**Comment by bastilian** [comment]
@adonispuente Have you tried removing the class here: https://github.com/RedHatInsights/vulnerability-ui/blob/master/src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js#L96

**Comment by adonispuente** [comment]
> @adonispuente Have you tried removing the class here: https://github.com/RedHatInsights/vulnerability-ui/blob/master/src/Components/SmartComponents/SystemDetailsPage/SystemDetailsPage.js#L96


https://github.com/RedHatInsights/vulnerability-ui/pull/2130

**Pull request merged**
