### PR TITLE
feat(THEEDGE-3581): add tab controls to display detail groups

### PR DESCRIPTION
**Pull request by acosferreira**
This PR add a tab to group details when exists an edge host added to the group.
In case only edge devices the focus will be on immutable
In case only conventional, no tabs displayed

image
image
image

### CODE REVIEW

**Comment by acosferreira** [comment]
this PR should be merged after https://github.com/RedHatInsights/edge-frontend/pull/762

**Review by mkholjuraev — APPROVED** [review]
LGTM! While testing locally, I did not face issues.

**Pull request merged**
