### PR TITLE
chore: Don't use extra span tag to render tab text

### PR DESCRIPTION
**Pull request by gkarat**
This makes the tabs headers on the Group details page not to render extra `span` tag inside `button`. This was caused by using unnecessary `TabTitleText` component.

### CODE REVIEW

**Comment by gkarat** [comment]
cc: @computercamplove

**Comment by computercamplove** [comment]
verified on local env, lgtm!

**Review by bastilian — APPROVED** [review]
LGTM! Thank you @gkarat!

**Comment by computercamplove** [comment]
@gkarat to merge we need to wait for resolved akamai issue?

**Pull request merged**
