### PR TITLE
feat(ESSNTL-3577): hide non-edge tabs

### PR DESCRIPTION
**Pull request by mkholjuraev**
Resolves: https://issues.redhat.com/browse/ESSNTL-3577

To test:

1. Go to Inventory table
2. Filter systems bay System Update method = rpm-ostree
3. open one of the systems filtered
4. verify that Patch, compliance tabs are disabled
5. Verify that on Vulnerability tab, a new design is shown according to the [mock](https://www.sketch.com/s/60a21d8c-d9c1-4c19-9011-460dd0d157de) and leads to Edge system detail page on button click

### CODE REVIEW

**Review by AsToNlele — APPROVED** [review]
Good job :smile:
Everything works great and thank you for adding those tests!
Just a small nitpick:
The "Go to Edge Management" button is missing "preview" in the URL, propably just add `isBeta()` to the link

**Comment by mkholjuraev** [comment]
Nice catch, will update the PR and merge

**Pull request merged**
