### PR TITLE
fix(RHINENG-9687): Push system type filter into URL, apply on refresh

### PR DESCRIPTION
**Pull request by mkholjuraev**
Fixes https://issues.redhat.com/browse/RHINENG-9687.

This PR is intended to address the comments related to the system type filter not being pushed into the URL and also not being reapplied between Conventional and Immutable tabs. 

To test:
1. Run the PR
2. Apply one/both of the system filter options
3. Observe that now the filter is applied to URL and you can open the page with the same filter in a new browser tab
4. Apply the filter, and switch to the immutable tab. 
5. Observe that when you switch back to conventional tab, still the previous system filter is still present

### CODE REVIEW

**Review by gkarat — COMMENTED** [review]
LGTM! @mkholjuraev, I think we would need to resolve conflicts first.

Please re-request review once it's done.

**Comment by mkholjuraev** [comment]
Conflicts are due to the reverted commit and will be auto resolved after this PR: https://github.com/RedHatInsights/insights-inventory-frontend/pull/2207. Putting in draft mode until then

**Comment by mkholjuraev** [comment]
@gkarat would you mind having a look at this? conflicts are resolved after #2207

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Review by gkarat — APPROVED** [review]

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.1.1) is older than required version (6.0.0)

**Pull request merged**
