### PR TITLE
fix(THEEDGE-3629): should not display Zero state when has edge systems

### PR DESCRIPTION
**Pull request by ldjebran**
Inventory Systems should not display Zero state when account has immutable systems

FIXES: https://issues.redhat.com/browse/THEEDGE-3629

bug-edge-only-systems-inventory-2023-10-23 12-15

### CODE REVIEW

**Comment by ldjebran** [comment]
rebased

**Comment by ldjebran** [comment]
rebased

**Comment by computercamplove** [comment]
works as expected, thank you @ldjebran !

**Comment by ldjebran** [comment]
rebased

**Review by mkholjuraev — APPROVED** [review]
LGTM!

**Pull request merged**
