### PR TITLE
feat(RHIF-254) Add Zero State to Inventory

### PR DESCRIPTION
**Pull request by adonispuente**
Adds zero state to inventory
Run inventory on an account with 0 systems and run inventory with
ENVIORNMENT=prod npm run start:proxy:beta

### CODE REVIEW

**Comment by adonispuente** [comment]
@computercamplove Do you have an idea why the ci test could be failing? It looks like a timeout error maybe while its navigating?

**Comment by computercamplove** [comment]
> @computercamplove Do you have an idea why the ci test could be failing? It looks like a timeout error maybe while its navigating?

@adonispuente yes,
This test just navigation - it navigates to Systems page without creating any host - so it's waited that there will be empty systems table. Since You added new view "Zero state" which doesn't exists in tests - it shows timeout because not able to find system table. I just need to update test or add new one.

i will update test and retest PR

**Comment by computercamplove** [comment]
@adonispuente why Groups page should have Inventory zero state? To create new group you don't need to have systems and Groups page the only place where you can create a group - should it be without Zero state or has own "zero state" but suggesting user to create a group, not registering system?

**Review by bastilian — APPROVED** [review]
Works and looks as intended with no hosts! Thank you @adonispuente!

**Comment by adonispuente** [comment]
@computercamplove When zero-state was created that was the originally ask, but now that groups are here, what youre saying makes sense. I'll confirm with UX and get back here

**Comment by computercamplove** [comment]
image
@adonispuente 
when no systems uploaded to account Inventory has this issue
Frontend route: https://env-ephemeral-khsfwv-3b0nk4r5.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com
Frontend login: jdoe | A1HbZXno7viF7x4Y

**Comment by adonispuente** [comment]
This only seems to be a problem in ee. Can you confirm @computercamplove

**Pull request merged**
