### PR TITLE
feat(RHINENG-9687): create system type filter

### PR DESCRIPTION
**Pull request by mkholjuraev**
Impements https://issues.redhat.com/browse/RHINENG-9687.

The new filter should only be visible to customers that have bootc images and when the feature is enabled. The filter should comply with the design in this mockup: https://www.figma.com/file/izOiimeI3i1a44dKEaFsUf/Systems-in-Bifrost?type=design&node-id=1016-41257&mode=design&t=ZYd83sqYOyalba6a-4

To test:
1. Run the PR
2. Navigate to the landing page in the Inventory page 
3. Observe that now there is a new 'System type' filter among others in the filters dropdown
4. Try filtering the table with package mode, observe that the request is made with `filter[system_profile][bootc_status][booted][image_digest]=nil`
5. Try filtering the table with image mode, and observe that the request is made with `filter[system_profile][bootc_status][booted][image_digest]=not_nil`
6. In general, play with it

### CODE REVIEW

**Comment by computercamplove** [comment]
@mkholjuraev i still see "System update method" filter 
image

**Comment by computercamplove** [comment]
Filter works as expected:
1. account without image mode systems doesn't see this filter
2. able to filter together with other filters
2. able to sort systems without resetting system type filter

minor issues:
1. filter is not saved in URL 
2. according to acceptance criteria "System update method" should be removed

**Review by johnsonm325 — APPROVED** [review]

**Comment by mkholjuraev** [comment]
Comments will be addressed in the next PR.

**Pull request merged**
