### PR TITLE
fix(HMS-2648): Show the OS major minor version for CentOS systems

### PR DESCRIPTION
**Pull request by mhuth**
https://issues.redhat.com/browse/HMS-2648

### CODE REVIEW

**Comment by mhuth** [comment]
Before patch:
Screenshot from 2023-09-29 12-16-16
Screenshot from 2023-09-29 12-16-21

After patch:
Screenshot from 2023-09-29 12-14-58
Screenshot from 2023-09-29 12-18-47

**Review by mkholjuraev — APPROVED** [review]
Works as expected, thank you @mhuth!

**Comment by mhuth** [comment]
Thanks for the review @mkholjuraev. Are you able to merge this PR for me too? :)  I don't have write access to the repo so I can't merge it unfortunately.  Thanks.

**Pull request merged**
