### PR TITLE
fix(THEEDGE-3564): Add missing update action button to edge systems

### PR DESCRIPTION
**Pull request by de1987**
Add missing update action button to edge systems.
[THEEDGE-3564](https://issues.redhat.com/browse/THEEDGE-3564)

image

### CODE REVIEW

**Comment by computercamplove** [comment]
1. when I'm in process to update edge system, after i click "Update system" button it redirect me to preview/insights/inventory/ - it should me redirect back to host's details
2. When i click "Update system" button i should see notification about Update  - i don't see this notification

**Comment by de1987** [comment]
> 1. when I'm in process to update edge system, after i click "Update system" button it redirect me to preview/insights/inventory/ - it should me redirect back to host's details
> 
>     2. When i click "Update system" button i should see notification about Update  - i don't see this notification

hey @computercamplove 
I fixed 1. but I need to push this fix to edge-management frontend.
Regarding 2. I'm checking if this is a limitation due to the federation.

**Comment by de1987** [comment]
@computercamplove done

**Comment by computercamplove** [comment]
@de1987 thank you! I see issues are resolved. Ping someone from interact-team to review PR

**Review by adonispuente — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
