### PR TITLE
fix(Tags): show all tags for all systems

### PR DESCRIPTION
**Pull request by mkholjuraev**
fixes: https://issues.redhat.com/browse/ESSNTL-3427

Removes all impacting filters from the tags list in the tag filter.

### CODE REVIEW

**Review by gkarat — CHANGES_REQUESTED** [review]
It looks like the tags filter is loading infinitely in *all* consumer applications that I could check, and also in Inventory in some cases: if you go to Inventory from any of the pages (e.g., 1. open Inventory, 2. check that the filter is working, 3. go to, e.g., Advisor and then navigate to Inventory again, 4. the filter is constantly loading). The issue is not present at console.stage.redhat.com/beta.

изображение

Also, it looks like in some circumstances, the filter windows is wider than other boxes (see the screenshot below). I remember this should have been fixed recently, and I also don't see this visual bug at console.stage.redhat.com/beta.

изображение

**Comment by computercamplove** [comment]
@gkarat this visual bug still present on console.stage.redhat.com/beta - https://issues.redhat.com/browse/ESSNTL-2639

**Review by Fewwy — APPROVED** [review]
Need to fix the visual bugs in the other PR though. :) Other than that LGTM

**Comment by mkholjuraev** [comment]
@Fewwy thanks for the review!

**Pull request merged**
