### PR TITLE
Chore: Update README With 'Common Problems Users Might Encounter' Section

### PR DESCRIPTION
**Pull request by LiorKGOW**
### Description

* This PR comes to address common installation problems that user might encounter when they first install our application or update to the latest version

* This is just a suggestion of course, in case someone sees a better way to write this is more then welcome to suggest it or add another common problem that might be useful to mention in this section 😇 

### Explanation About the commits included

1. After a conversation with @mkholjuraev, we thought a README update might be needed with the case I mentioned in the first commit

2. The second commit fixes typos that were in the README in 'Release process change in stage env' section

### CODE REVIEW

**Comment by LiorKGOW** [comment]
@RedHatInsights/team-interact 

Do you guys think this is necessary? 
Do you have a better suggestion?

**Review by leSamo — APPROVED** [review]
Nice one, thanks for propagating information in visible places.

**Pull request merged**
