### PR TITLE
fix(ESSNTL-4745):Enable custom dates for lastSeen filter

### PR DESCRIPTION
**Pull request by adonispuente**
This PR enables custom Dates for last seen filter and addresses additional edgecases discussed here : https://issues.redhat.com/browse/ESSNTL-4746 

To test, select the last seen filter custom option,
type in unique characters like {{' , '2023-04-21' in the end date field and make sure it doesnt break anything.

For the second edge case, input two identical FUTURE dates in first the end date and then in the start date inputs. Then erase the end date input. Verify that nothing breaks.

### CODE REVIEW

**Comment by gkarat** [comment]
This merge with master ^ should fix the failing cy test not related to this PR.

**Comment by gkarat** [comment]
This merge with master ^ should fix the failing cy test not related to this PR.

**Comment by adonispuente** [comment]
@AsToNlele they pass now

**Review by gkarat — APPROVED** [review]
works on my end fine and code-wise also looks good! thanks @adonispuente

**Pull request merged**
