### PR TITLE
chore(ImmutableDevices): allow passing onRowClick function

### PR DESCRIPTION
**Pull request by mkholjuraev**
Enables consumer apps to pass their own onRowClick function. This will enable to have different behavior of system name column depending on the consumer.

### CODE REVIEW

**Comment by bastilian** [comment]
Wouldn't the `onRowClick` of the TitleColumn[0] (vie the entity) already allow to do what this is meant to allow? 

[0] https://github.com/RedHatInsights/insights-inventory-frontend/blob/master/src/components/InventoryTable/TitleColumn.js#L12

**Comment by bastilian** [comment]
> Do we want to tweak TitleColumn?

We always want to enhance what we have instead of introducing something new. We have had several occasions in the past where we simply wanted to change where the link navigates to. It seems to me it is time to enhance the `onRowClick` of the TitleColum.

**Comment by mkholjuraev** [comment]
> It seems to me it is time to enhance the `onRowClick` of the TitleColum.

I am happy to improve. I am thinking about what would be the best way to go as TitleColumn is used in almost all places where InventoryTable is consumed. It is provided to default columns. Would I need to pass a new `onTitleColumnClick` function from top to down the TitleColumn component?

**Comment by mkholjuraev** [comment]
@bastilian I investigated the scope of changes needed to improve the TitleColumn. It feels to me that it has large-scale changes and testing are needed. I would not want to be blocked with this while there are more important tasks waiting for edge-parity work. I can create a task for this improvement.

**Comment by bastilian** [comment]
@mkholjuraev What changes would be "large-scale"? It would likely just need the addition of a `onRowClick` property to the entities provided to the InventoryTable.

**Comment by mkholjuraev** [comment]
I am not able to find a clean way to pass onRowClick to TitleColumn. Can you clarify your idea? By large-scale, I mean passing this onRowClick would require me to make changes in multiple functions and test the change in multiple applications to make sure it does not affect them.

**Comment by bastilian** [comment]
@mkholjuraev Is there no `getEntities` or fetch function that can add a `onRowClick` prop to each entity it returns?

**Comment by mkholjuraev** [comment]
Putting in draft mode for  https://github.com/RedHatInsights/insights-inventory-frontend/pull/2087

**Pull request closed without merging**
