### PR TITLE
ESSNTL-4883 - ROS tab not visible in Inventory fix

### PR DESCRIPTION
**Pull request by jiridostal**
Fixes issue where Inventory does not display ROS tab correctly based on the cloud provider.

### CODE REVIEW

**Review by gkarat — APPROVED** [review]
I can see the tab now appearing. Not sure it's correct or not, but I saw the welcome page rendered within the tab...

image

**Comment by Fewwy** [comment]
@jiridostal Why package-lock is added to this PR?

**Review by mkholjuraev — APPROVED** [review]
LGTM, tested locally

**Review by PreetiW — APPROVED** [review]
I tested the PR and ROS tab is now visible in the inventory detail page. Thanks @jiridostal for the fix 🙌🏻

**Pull request merged**
