### PR TITLE
fix(ESSNTL-3760): handle insights disconnected hosts for patch, advis…

### PR DESCRIPTION
**Pull request by mkholjuraev**
Fixes: https://issues.redhat.com/browse/ESSNTL-3760.

This moves insights disconnected systems handling from applications inside the tab to Inventory itself. By having this we have more consistency and we will not be required to load those apps, instead Inventory shows the NotConnected component directly,

To test:
1. Find `ci-vm-10-0-206-95.hosted.upshift.rdu2.redhat.com` host which is of disconnected systems
2. Click and open details
3. Move to Advisor, vuln and Patch tabs
4. Observe that each app is not loaded, instead NotConnected component is shown directly

### CODE REVIEW

**Comment by Fewwy** [comment]
When I tried to open a patch tab in the single system page
image

**Comment by mkholjuraev** [comment]
Can you make sure that you have pulled latest commits from the PR? it works as expected on my side

**Comment by mkholjuraev** [comment]
@Fewwy I have once more tested this locally and everything seemed to be fine

**Comment by mkholjuraev** [comment]
@computercamplove Wondering if this ci.int test failures are due to IQE tests?

**Comment by Fewwy** [comment]
It seems that I somehow missed the instruction :D sorry
I tested it again and it works as expected

**Review by Fewwy — APPROVED** [review]

**Pull request merged**
