### PR TITLE
ESSNTL-4143: Add IQE UI smoke tests to pr_check

### PR DESCRIPTION
**Pull request by computercamplove**
Add IQE UI smoke tests to pr_check [ESSNTL-4143](https://issues.redhat.com/browse/ESSNTL-4143)

For now, I just added 9 basic QE tests.

### CODE REVIEW

**Comment by computercamplove** [comment]
waiting for https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/57093 to test it

**Comment by computercamplove** [comment]
Rebuilding image

**Review by gkarat — APPROVED** [review]
LGTM! The smoke tests are executed in pr_check and succeeded for this PR.

**Comment by LightOfHeaven1994** [comment]
LGTM, great work!

**Comment by Fewwy** [comment]
You need to update the pr with fresh master but other than that LGTM

**Review by Fewwy — APPROVED** [review]

**Pull request merged**
