### PR TITLE
chore(commitlint): Enable commitlint on all branches

### PR DESCRIPTION
**Pull request by gkarat**
Enable commitlint in all branches.

### CODE REVIEW

**Comment by bastilian** [comment]
I have seen in other repos that running commitlint on master can sometimes be iffy, when a PR gets squashed and merged and the PR title then commit message does not conform.
It requires then to amend the last commit and force push a new master.

I'm honestly not sure if that is good or bad though...

**Comment by mkholjuraev** [comment]
> Let's see what happens, maybe it's good to run it on master. Thank you @gkarat!

Hmm, we wanted not to have to commit lint on the master branch, rather we [wanted](https://redhat-internal.slack.com/archives/C02T90PLJ5V/p1696599287638499) it to happen in the PR phase. @gkarat does it PR implement that thing?

**Comment by bastilian** [comment]
@mkholjuraev This PR will enable running commitlint on the master branch, and it is not a bad thing. The only annoying thing will be if we aren't carful when writing the commit message when we squash and merge.

**Comment by mkholjuraev** [comment]
@bastilian yup, we have already seen multiple times those annoying situations as you described. Devs that are not aware of the commit lint tend to merge commits that do not conform to the lint and they change locally, rebase, change commit history, and then force push. Later on, when we fully migrate to containers, if the commit history is changed it will lead to confusion as we faced several weeks ago with the insights dashboard app.

**Comment by bastilian** [comment]
@mkholjuraev There is no way we can verify commit messages in master, without running them on master. And to keep the history in master proper, we will need to rewrite offending commit messages.

**Pull request merged**
